export const tagsData = {
  sage: {
    categories: {
      Surroundings: [
        { label: "Mountains", conflict: ["Coastline"] },
        { label: "Coastline", conflict: ["Mountains"] },
        { label: "Forest", conflict: [] },
        { label: "Meadow", conflict: [] },
        { label: "River", conflict: ["Coastline"] },
        { label: "Lake", conflict: ["Coastline"] },
      ],
      Climate: [
        { label: "Cloudy", conflict: ["Sufficient Sun"] },
        { label: "Sufficient Sun", conflict: ["Cloudy"] },
        { label: "Cold Winters", conflict: ["Mild"] },
        { label: "Mild", conflict: ["Cold Winters"] },
      ],
      Vegetables: [
        { label: "Tomatoes", conflict: ["Cold Winters", "Cloudy", "Mountains"] },
        { label: "Peppers", conflict: ["Cold Winters", "Cloudy", "Mountains"] },
        { label: "Zucchini", conflict: ["Cold Winters", "Mountains"] },
        { label: "Eggplant", conflict: ["Cold Winters", "Cloudy", "Mountains"] },
        { label: "Onions", conflict: [] },
        { label: "Potatoes", conflict: [] },
        { label: "Cabbage", conflict: [] },
        { label: "Carrots", conflict: [] },
        { label: "Beets", conflict: [] },
        { label: "Kale", conflict: [] },
        { label: "Artichokes", conflict: ["Cold Winters", "Mountains"] },
        { label: "Cauliflower", conflict: [] },
        { label: "Turnips", conflict: [] },
        { label: "Leeks", conflict: [] },
        { label: "Garlic", conflict: [] },
        { label: "Rye", conflict: [] },
      ],
      "Fruits & Nuts": [
        { label: "Olives", conflict: ["Cold Winters", "Mountains"] },
        { label: "Citrus", conflict: ["Cold Winters", "Mountains"] },
        { label: "Almonds", conflict: ["Cold Winters", "Mountains"] },
        { label: "Avocados", conflict: ["Cold Winters", "Mountains"] },
        { label: "Figs", conflict: ["Cold Winters", "Mountains"] },
        { label: "Pomegranates", conflict: ["Cold Winters", "Mountains"] },
        { label: "Apples", conflict: [] },
        { label: "Pears", conflict: [] },
        { label: "Plums", conflict: [] },
        { label: "Currants", conflict: [] },
        { label: "Grapes", conflict: ["Cloudy"] },
        { label: "Chestnuts", conflict: [] },
        { label: "Apricots", conflict: ["Cold Winters", "Mountains"] },
        { label: "Peaches", conflict: ["Cold Winters", "Mountains"] },
        { label: "Berries", conflict: [] },
      ],
      "Other Food Production": [
        { label: "Dairy", conflict: [] },
        { label: "Honey", conflict: [] },
      ],
      "Alternative Energy": [
        { label: "High Solar", conflict: ["Cloudy"] },
        { label: "High Wind", conflict: [] },
        { label: "Hydroelectric Potential", conflict: [] },
      ],
    },
  },
};
